### ISSUE TITLE
geoviews feature ocean with bokeh

### ISSUE THREAD

**Issue by Maurau** [pyviz/geoviews#148]
Hello!
It appears that using bokeh removes a part of the ocean geoviews feature : 

![pic2](https://user-images.githubusercontent.com/38098729/38570821-05965d46-3cef-11e8-9855-d5ed3ad143fe.png)
![pic1](https://user-images.githubusercontent.com/38098729/38570822-05b75d52-3cef-11e8-91e1-600cecee4a04.png)

**Comment by philippjfr** [comment]
Thanks for the bug report, I suspect it has something to do with the z-ordering and may have to be fixed upstream in bokeh.

**Comment by Maurau** [comment]
Yes probably !
I also tried to use an ocean shapefile but same issue.


![pic3](https://user-images.githubusercontent.com/38098729/38571494-f0c7062a-3cf0-11e8-9e3b-76e25324cb8d.png)

Do you have an idea how to overpass this issue?

**Comment by philippjfr** [comment]
@Maurau For now I'd probably just overlay the land ``gf.ocean * gf.land`` on top, which should cover up the issue.

**Comment by Maurau** [comment]
@philippjfr Actually my point was to use the ocean shapefile to recover the pixels that are on the border of the continents, so that it appears cleaner ! 
![bildschirmfoto vom 2018-05-24 12-44-35](https://user-images.githubusercontent.com/38098729/40481054-b529c3b6-5f3f-11e8-8260-8dde50a03cdb.png)

**Comment by philippjfr** [comment]
Makes sense, and it's quite frustrating. I realize now it's not the z-ordering that's the problem but that bokeh does not yet support rendering polygons with holes, which explains why the polygons at the edges are showing up but the americas are not.
