### ISSUE TITLE
Changing levels in a dynamic map

### ISSUE THREAD

**Issue by jlstevens** [pyviz/geoviews#20]
One of the user stories involves modifying the contour levels with a slider. This is a plot option on `FilledContours` although it is then translated into kwargs for `iris.plot.contourf`.

Changing the options of the elements within a `DynamicMap` doesn't reflect this change. Although this is a known limitation for many elements due to the way artists are initialized and updated, I was wondering if it was possible to get this working given that every frame is redrawn by the `iris.plot.contourf` calls.

**Comment by philippjfr** [comment]
>Changing the options of the elements within a DynamicMap doesn't reflect this change. Although this is a known limitation for many elements due to the way artists are initialized and updated, I was wondering if it was possible to get this working given that every frame is redrawn by the iris.plot.contourf calls.

It's a bug if it doesn't respect the levels at all or are you saying it respects only the option set on the first Element and if that changes later it is not respected?

**Comment by jlstevens** [comment]
> ... it respects only the option set on the first Element and if that changes later it is not respected?

This is what I am referring to. I know we've encountered this issue before but now it has cropped up for something specific a user would like to use.

**Comment by philippjfr** [comment]
Could you print the the levels in the ``LineContourPlot.get_data`` method. Afaik this should already be working as we have this line in ``ElementPlot.update_frame``

```
        if element is not None:
            self.set_param(**self.lookup_options(element, 'plot').options)
```

**Comment by philippjfr** [comment]
This works fine now.
