### ISSUE TITLE
Releasing new tag uploads only to pyviz/label/dev conda channel

### ISSUE THREAD

**Issue by philippjfr** [pyviz/geoviews#201]
When tagging a new release Travis only seems to upload the package to label/dev. This build is an example: https://travis-ci.org/pyviz/pyviz/jobs/401209417

For now I've manually uploaded 1.5.2 packages to label/main and label/earthsim. @ceball

**Comment by ceball** [comment]
Oops, sorry, there was another typo in my recent PR to simplify the travis config:

<img width="729" alt="screen shot 2018-07-08 at 7 40 48 am" src="https://user-images.githubusercontent.com/1929/42417441-506e3c2a-8282-11e8-9974-b5e8e3435791.png">

Should be LABELS_REL and CHANS_REL, not _DEV

> For now I've manually uploaded 1.5.2 packages to label/main and label/earthsim

When you say manually uploaded to x, do you mean added the label x? (There's no need to upload multiple times.)

Separately, the earthsim label won't be automated (at least, that's not the idea in my mind). During earthsim dev, we'll use the pyviz dev channel (maybe via a 'dev' developments.txt file). But users will get a deliberately pinned/known environment, and the earthsim label is part of that.

**Comment by ceball** [comment]
(I'm not sure how to understand the travis link you added...it's to pyviz?)

**Comment by philippjfr** [comment]
>(I'm not sure how to understand the travis link you added...it's to pyviz?)

Wrong link sorry but sounds like you've figured it out anyway.
