### ISSUE TITLE
Masking point inside cartopy coastline and slow perfomance creating cartopy feature

### ISSUE THREAD

**Issue by neocronomican** [pyviz/geoviews#213]
Dear all,

I am using holoview and geoview. I want to know is it possible to keep all the value inside the coastline (masking/muting all value outside coastline)?

![](https://user-images.githubusercontent.com/37390012/43490539-0afabeba-955c-11e8-8973-a47775e66019.png)

I also slow perfomance when I try to make feature by using geoview.feature. Any suggestion?

```
import cartopy.feature as cf
import geoviews.feature as gf

ocean =  cf.GSHHSFeature(scale='l', edgecolor='red', facecolor='white')
gf.Feature(ocean)

```

**Comment by jlstevens** [comment]
I wonder if a workaround would be possible if we had support for polygons with holes (everything outside the hole would be masked...)

**Comment by philippjfr** [comment]
This is out-of-scope for GeoViews, these kinds of operations should be handled by libraries like shapely or cartopy.

**Comment by philippjfr** [comment]
As a workaround you could just overlay the ocean feature, which will effectively mask it.
