### ISSUE TITLE
Cannot update WMTS url in a DynamicMap

### ISSUE THREAD

**Issue by jlstevens** [pyviz/geoviews#215]
Here is an example of what I would expect to work:

```python
class Example(param.Parameterized):

    def __init__(self, url='<WMTS URL>'):
        self.url_stream = hv.streams.Stream.define('url', url=url)()

    def url(self, url):
        self.url_stream.event(url=url)

    def callback(self, url):
        return gv.WMTS(url, extents=(-180, -90, 180, 90), crs=ccrs.PlateCarree())

    def __call__(self):
        return gv.DynamicMap(self.callback, streams=[self.url_stream])
```

Which can then be used to create a plot with:

```python
plot = Example()
plot()
```

Then using the ``plot`` handle, you would expect to be able to update the WMTS via the dynamic map with:

```python
plot.url('<NEW WMTS URL>')
```

I would expect this to update the plot as ``callback`` is invoked with the new URL and it returns a new ``WMTS`` element. HoloViews version is ``1.11.0a1.post10+g5e00a9af`` and the GeoViews version is '1.5.3'.

**Comment by philippjfr** [comment]
There was a bug in GeoViews that meant the URL was not updated correctly, however even with that fix applied there are certain issues with the way tiles are cached: https://github.com/bokeh/bokeh/issues/8164

**Comment by philippjfr** [comment]
Since the bug in geoviews has been fixed and there's now an issue about the bug in bokeh filed upstream I'll close this.
