### ISSUE TITLE
Disabling sliders for exported DynamicMaps

### ISSUE THREAD

**Issue by jbednar** [pyviz/geoviews#22]
It's great that a DynamicMap will export to HTML with the currently visible data and with sliders that show that more data is available.  However, because the sliders don't actually work in the exported copy (e.g. the last few cells of http://geo.holoviews.org/Iris_Datasets_II.html), it's very confusing to users, who are likely to think that the software is broken or buggy.  We should either gray out the sliders, or at least make them not draggable, so that it is clear that the exported image is just an example and does not provide the full power of the Python version. 

Alternatively, maybe it would be good for a user to be able to specify some default spacing on the dimensions, to be able to export the DynamicMap as a partially usable HoloMap?

**Comment by jbednar** [comment]
Or always do a 2x2x2x2... cross product, i.e. with at least two values for every slider, so that all sliders work?

**Comment by philippjfr** [comment]
This issue exists in various forms on the holoviews repo, so I'll close it here.
