### ISSUE TITLE
How do debug Quadmesh issue with curvilinear coordinates?

### ISSUE THREAD

**Issue by rsignell-usgs** [pyviz/geoviews#222]
I'm trying to visualize some curvilinear model output from the ROMS ocean model with quadmesh.  The [xarray quadmesh example from the geoviews docs](http://geo.holoviews.org/gallery/bokeh/xarray_quadmesh.html) works perfectly, but when I [try my own example](https://nbviewer.jupyter.org/gist/rsignell-usgs/f1aa53894e995820da1250149f586cda
), I get nothing, even though my geoviews object looks the same to me:
* Geoviews example (works): 
    ```
    Coordinates:
     * time     (time) datetime64[ns] 1980-09-16T12:00:00 1980-10-17 ...
        xc       (y, x) float64 189.2 189.4 189.6 189.7 189.9 190.1 190.2 190.4 ...
        yc       (y, x) float64 16.53 16.78 17.02 17.27 17.51 17.76 18.0 18.25 ...
    ...
    :HoloMap   [time]
       :QuadMesh   [xc,yc]   (Tair)
    ```

* My example (doesn't work):
    ```
    Coordinates:
        lon_rho   (eta_rho, xi_rho) float64 ...
        lat_rho   (eta_rho, xi_rho) float64 ...
      * time      (time) datetime64[ns] 2013-01-03T01:00:00 2013-01-03T02:00:00 ...
    ...
    :HoloMap   [time]
       :QuadMesh   [lon_rho,lat_rho]   (Hwave)
    ```

[The notebook](https://nbviewer.jupyter.org/gist/rsignell-usgs/f1aa53894e995820da1250149f586cda) executes with no python or javascript errors errors, but hangs in a way that is not interruptable by a kernel interrupt when the cell after cell [13] is called:
```
%%opts QuadMesh [width=700 height=350]
tiles * qmeshes2
```
Any ideas how to debug?  
(p.s. my notebook should be reproducible since it accesses data in `xarray` via OPeNDAP)

**Comment by philippjfr** [comment]
I suspect this is simply because large quadmeshes are very inefficient when plotted with bokeh because each grid cell is an individual polygon. I think we may just have to add warnings for large grids, and suggest that the mesh should be rasterized with datashader. That should at least work although that too requires significant optimization.

**Comment by rsignell-usgs** [comment]
@philippjfr, okay, I'll use datashader.    But I think there might be some other problem here, because the example that works has 6348 quads to render at each time step, and mine doesn't work even with 3060 quads to render.  This notebook should be able to be run without changes:
https://nbviewer.jupyter.org/gist/rsignell-usgs/f1aa53894e995820da1250149f586cda

**Comment by philippjfr** [comment]
I believe the slowdown is unrelated to anything in geoviews, and it's something to do with accessing the file, e.g. if I try to run this on its own:

```
ds.Hwave[0:2,::10,::10]
```

It hangs in the same way.
