### ISSUE TITLE
Paths should have fixed aspect ratio

### ISSUE THREAD

**Issue by jsignell** [pyviz/geoviews#223]
**Version Info:**
geoviews: 1.5.4a5
holoviews: 1.11.0a3.post7+g221c4df
bokeh: 1.0.0dev5

I came across this while going through the earthsim drawing example. When a gv.Path element is rendered with no other elements the aspect ratio is not fixed. 

<img width="835" alt="screen shot 2018-08-20 at 5 03 57 pm" src="https://user-images.githubusercontent.com/4806877/44366608-2f954d00-a49b-11e8-9bad-f97d2489014e.png">

Just for a bit more info the coordinate system is known and shapely preserves the aspect: 
<img width="498" alt="screen shot 2018-08-20 at 5 08 46 pm" src="https://user-images.githubusercontent.com/4806877/44366773-d679e900-a49b-11e8-8c8d-c977ac2c7a50.png">

**Comment by philippjfr** [comment]
This is a general issue about aspect ratios which affects HoloViews as well and is sufficiently covered there so I'll close.
