### ISSUE TITLE
.options and .opts broken inside bokeh server when geoviews is imported

### ISSUE THREAD

**Issue by felixpatzelt** [pyviz/geoviews#229]
Importing geoviews breaks holoviews' .opts and .options methods inside a bokeh server (but not inside a jupyter notebook).

<img width="1506" alt="without_geoviews" src="https://user-images.githubusercontent.com/771204/45501012-5d12a500-b780-11e8-941d-f1ab7f3ef2e7.png">

<img width="1044" alt="with_geoviews" src="https://user-images.githubusercontent.com/771204/45501062-84697200-b780-11e8-9e20-a8006b58e600.png">

```python
# minimal_example.py
# usage: bokeh serve --show minimal_example.py

import holoviews as hv
from bokeh.plotting import curdoc

# comment the line below and then options work
import geoviews as gv

renderer = hv.renderer('bokeh').instance(mode='server')

xs = range(-10,11)
ys = [100-x**2 for x in xs]
c = hv.Curve((xs,ys)).options(width=800) # options are ignored when geoviews is imported 

p = renderer.get_plot(c).state
curdoc().add_root(p)
```
geoviews 1.5.1
holoviews 1.10.7
bokeh 0.13.0

**Comment by philippjfr** [comment]
Thanks, certainly very odd.

**Comment by philippjfr** [comment]
I think I see what's going on here now, the default backend in holoviews is still matplotlib, which means that by default the options will be applied to that backend. In a notebook running the extension will switch the backend allowing you to set options as expected.

**Comment by felixpatzelt** [comment]
Thanks, you might be right about this. Moving `renderer = hv.renderer('bokeh').instance(mode='server')` up so the renderer is set before importing geoviews seems to solve the issue. It is certainly a strange and unexpected side-effect.
