### ISSUE TITLE
using identical colormaps for netcdf dataset

### ISSUE THREAD

**Issue by rr5577** [pyviz/geoviews#232]
I have a netcdf dataset
```
<xarray.Dataset>
Dimensions:  (level: 2, time: 24, x: 44, y: 36)
Coordinates:
  * time     (time) datetime64[ns] 2015-01-01 2015-01-01T01:00:00 ...
  * level    (level) int32 1 2
  * x        (x) float64 4.481e+05 4.481e+05 4.481e+05 4.481e+05 4.482e+05 ...
  * y        (y) float64 5.165e+06 5.165e+06 5.165e+06 5.165e+06 5.165e+06 ...
Data variables:
    SG1-PQ   (time, level, y, x) float64 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 ...
    SG2-LQ   (time, level, y, x) float64 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 ...
    SG3-PO   (time, level, y, x) float64 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 ...`
```
I´m displaying it on a map
```
# test plot
kdims = ["time","level",'x', 'y']
vdims = ['SG2-LQ']
xr_dataset = gv.Dataset(xds, kdims=kdims, vdims=vdims,crs=crs.UTM(zone=33))
rasterize(xr_dataset.to(gv.Image, ['x', 'y'],dynamic=True), precompute=True,)\
                        .options(tools=['hover'],alpha=0.85,cmap='viridis',colorbar=True,xaxis=None,yaxis=None) * gts.StamenTerrain
```

For now, each hour uses the full range of its values for the colorramp
![image](https://user-images.githubusercontent.com/31547476/46011428-139e5000-c0c6-11e8-8052-7f19afe6e591.png) 
![image](https://user-images.githubusercontent.com/31547476/46011475-3cbee080-c0c6-11e8-87ae-d73f84815c1f.png)

Is it possible to get one classified range (e.g. 0-10,11-20,21-30...) and corresponding color(s) that´s used for every hour?
I tried to use `redim.range` from the [example in the guide](http://geoviews.org/user_guide/Gridded_Datasets_I.html), but couldn´t get it to work.

**Comment by ahuang11** [comment]
I think `framewise=False` if you have it as a HoloMap or `axiswise=False` if you have it as subplots.

```plot_object.options(tools=['hover'],alpha=0.85,cmap='viridis',colorbar=True,xaxis=None,yaxis=None,framewise=False)```

You may also use redim.range like

`plot_object.redim.range(**{'SG2-LQ': (0, 1000)})`

**Comment by rr5577** [comment]
Thanks for the advice!
`framewise=False` and `axiswise=False` don´t seem to work in combination with `rasterize()`, as soon as I don´t use that, the colorbar is the same for all hours.

`plot_object.redim.range(**{'SG2-LQ': (0, 1000)})` works with `rasterize()` as well.
So, that will work to give me 1 range for all the hours, is there an option to create classes (e.g. 0-10,11-20,etc)?

**Comment by jbednar** [comment]
framewise and axiswise should have worked with rasterize, so it would be good to have a reproducible example that we can test.  Maybe you are applying the options to the original Image and not to the rasterized result?  You could try moving your .options() call to the outermost object.

**Comment by rr5577** [comment]
I thought I did put the options to the rasterized result, but will try again.

Here´s the test notebook and netcdf files:
[netcdftest.zip](https://github.com/pyviz/geoviews/files/2419947/netcdftest.zip)

**Comment by jbednar** [comment]
Thanks; that runs fine.  And now I notice that you are using a DynamicMap (`dynamic=True`).  A DynamicMap can't calculate the ranges automatically, because at any instant the callback function might return some value outside of the range that has been seen so far.  So there's no way to support framewise=False.  Instead you'll just need to provide an explicit range of your choosing, as Andrew suggested.  I think there should have been an error message for setting framewise to False, but because framewise=False is the default value for HoloMaps, I think we decided it would be too irritating to provide such a message.

**Comment by rr5577** [comment]
Ok, that makes sense, thanks for the explanation.
So I just need to find a way to classify and display the classes now.

**Comment by jbednar** [comment]
Great! I'm not sure what your needs for that second part are; maybe open a separate issue explaining that in more detail with an example of what you'd like it to do.
