### ISSUE TITLE
Plot contains no data, and coordinate axes are wrong

### ISSUE THREAD

**Issue by RPrudden** [pyviz/geoviews#235]
I have some working code in holoviews which displays a dataset (constructed from an xarray dataset).

```python
(hv_ds.to(hv.Image, ["projection_x_coordinate", 
"projection_y_coordinate"])).redim.range(rainfall=(0,100))
```

<img src="https://user-images.githubusercontent.com/9357195/46358179-5a5bef00-c65e-11e8-885a-492e26199210.png" width="200" height="200">

However, when I try to do the equivalent in geoviews the plot does not contain any data. Also, the axes are completely different. I think geoviews is only plotting a small section of the data, but I have no idea why.

```python
import geoviews as gv
(hv_ds.to(gv.Image, ["projection_x_coordinate", 
"projection_y_coordinate"])).redim.range(rainfall=(0,100))
```

<img src="https://user-images.githubusercontent.com/9357195/46358191-63e55700-c65e-11e8-9088-41a3ebecd6ac.png" width="200" height="200">

<h3>Extra information</h3>
The geoviews version also runs considerably slower than the holoviews version - on the order of minutes, rather than seconds. It gave some warnings while it was running:

```
/opt/conda/lib/python3.6/site-packages/numpy/core/_methods.py:26: RuntimeWarning: invalid value encountered in reduce
  return umr_maximum(a, axis, None, out, keepdims)
```

I have also tried loading the data from iris, and regridding into latitude/longitude coordinates, but the results were much the same.

**Comment by jbednar** [comment]
You just need to tell GeoViews what coordinate system your data is in, using the `crs` parameter accepted by GeoViews objects.  Without that declaration, it assumes your data is in PlateCaree, which is clearly not the case here.  Maybe pass `crs=crs.GOOGLE_MERCATOR` (given the size of those coordinates)?

**Comment by RPrudden** [comment]
Thanks, this helped! I switched to the geoviews Dataset and used
```python 
gv_ds = gv.Dataset(xr_ds, crs=cube.coord_system().as_cartopy_crs())
```
Strangely, the limits of the cartopy CRS seem to be different than in Iris so that part of the data is cut off. The original is in a TransverseMercator coordinate system, but in cartopy it is mapped to OSGB.

<img src="https://user-images.githubusercontent.com/9357195/46363636-7e71fd00-c66b-11e8-87ce-2d9bace7995b.png" width="200" height="200">

But I think this issue is either an Iris or a dataset issue, rather than geoviews.

**Comment by ahuang11** [comment]
> You just need to tell GeoViews what coordinate system your data is in, using the `crs` parameter accepted by GeoViews objects. Without that declaration, it assumes your data is in PlateCaree, which is clearly not the case here. Maybe pass `crs=crs.GOOGLE_MERCATOR` (given the size of those coordinates)?

I think GeoViews needs its own FAQ about this heh
