### ISSUE TITLE
Plot polygons with a single color

### ISSUE THREAD

**Issue by talbertc-usgs** [pyviz/geoviews#247]
Thank you for this great package.  Unless I'm missing something there doesn't seem to be an easy means to plot polygons with a single color.  I did see in the Katrina example one way to do this, but looping over all the individual geometries, and setting the color on each shape, seems like a lot of overhead for such a simple task.

`nybb = gpd.read_file(gpd.datasets.get_path('nybb'))
poly_data = nybb.to_crs(ccrs.GOOGLE_MERCATOR.proj4_init)
polys = gv.Polygons(poly_data, vdims=['BoroName'], crs=ccrs.GOOGLE_MERCATOR)

polys.options(line_color='red', line_alpha=0.3, color='red')

polys.options(line_color='red', line_alpha=0.3, fill_color='red')`

both result in a dark purple fill color:
![image](https://user-images.githubusercontent.com/23191658/47325095-8d6f1e00-d61f-11e8-9d07-46c7ee1229ef.png)

**Comment by philippjfr** [comment]
This is a case of perhaps confusing defaults, which enables colormapping for the value dimension. You can try setting the ``color_index=None``. This should be addressed in the next major release.

**Comment by talbertc-usgs** [comment]
Amazing response time!  

Worked like a charm.

**Comment by philippjfr** [comment]
This issue should resolve itself once HoloViews 1.13.0 is out which removes `color_index`.
