### ISSUE TITLE
Question re angle wrapping

### ISSUE THREAD

**Issue by ea42gh** [pyviz/geoviews#261]
Should gv.Path unwrap the angles internally,
or should it be up to the user calling gv.Path?
![gvpath](https://user-images.githubusercontent.com/13033479/49681754-0530c500-fa75-11e8-8934-cb303c1c644f.png)

**Comment by philippjfr** [comment]
It should handle longitude wrapping but out-of-bounds latitudes are not valid. I also doubt it will handle wrapping from paths which span more than 360 degrees in longitude properly.

**Comment by jbednar** [comment]
Not sure what you mean by out of bounds latitudes; those points all seem to be between +/- 60 in latitude.

**Comment by philippjfr** [comment]
Yes, I was just very confused by the plot on the left, I see now what it represents.

**Comment by ea42gh** [comment]
When you say it should handle longitude wrapping, do you intend to
modify gv.Path to remove that horizontal line?
Or is it still up to the user of hv.Path?

**Comment by philippjfr** [comment]
>When you say it should handle longitude wrapping, do you intend to modify gv.Path to remove that horizontal line?

The project operation should do that for you. Could you provide the code used to generate the example? Discussing things in the abstract is rarely helpful.

**Comment by ea42gh** [comment]
```
lon = np.linspace(90, 360+90, 100)%360.
lat = np.linspace(-60,60, 100)
gf.coastline*gv.Path([(lon,lat)])+hv.Curve(lon)*hv.Curve(lat)
```
and
```
lon = np.linspace(0, 360, 100)
lat = np.linspace(0,180+60, 100) % 180 - 90
gf.coastline*gv.Path([(lon,lat)])+hv.Curve(lon)*hv.Curve(lat)
```

The problem is the branch cut: gv.Path draws connections that should not be there.
A fix would be to break the path into pieces each time we cross the boundary,
with some care taken to draw the Path to the edge of the plotted geographical area.

Nasty piece of code that calls for a utility function...

**Comment by philippjfr** [comment]
I think the problem here is simply that you are wrapping the coordinates with the modulo, if you leave off the modulo it will wrap it correctly for you:

```python
lon = np.linspace(90, 360+90, 100)
lat = np.linspace(-60,60, 100)
gf.coastline*gv.Path([(lon,lat)])+hv.Curve(lon)*hv.Curve(lat)
```

![bokeh_plot](https://user-images.githubusercontent.com/1550771/49691633-d848e480-fb3e-11e8-91b0-41be352ed2ad.png)

**Comment by ea42gh** [comment]
It misses half the path that way

**Comment by ea42gh** [comment]
continuity of paths (contd) Consider the following example
```
class PlaneWatcher(param.Parameterized):
    step = param.Integer(0, bounds=(0,None))
    
    def __init__(self, **params ):
        self.lonlat = (np.linspace(0, 40, 5), np.linspace(-90,10, 5))
        self.proj   = crs.LambertConformal()
        #self.proj = crs.PlateCarree()
        super(PlaneWatcher,self).__init__(**params)

    @param.depends("step")
    def view_plane(self):
        self.lonlat = ((self.lonlat[0]+1+180)%360-180, (self.lonlat[1]+1 + 90)%180-90)
        h = gf.coastline*gf.ocean *\
            gv.Points( self.lonlat ).options(size=5,color='darkblue', tools=['hover'])*\
            gv.Path( [self.lonlat] ).options(color='red', projection=self.proj)
        return h.relabel('step=%d'%self.step).options( global_extent=True, width=500, height=475, projection=self.proj )
       
    def view(self):
        return hv.DynamicMap( self.view_plane )

obj = PlaneWatcher()

player = Player(length=1000, interval=10)
player.width=400
player.loop_policy = 'loop'
player.link(obj, value='step')
pn.Column(obj.view(), pn.Row(pn.Spacer(width=200),player))
```

If you leave this running long enough, you will also see points coming in from the lower left
from outside the projected image

**Comment by ea42gh** [comment]
![bokeh_plot](https://user-images.githubusercontent.com/13033479/49748455-b00ed200-fc73-11e8-9ae5-96f36707247a.png)

**Comment by ea42gh** [comment]
Don't know what happens to the coastline with proj LambertCylindrical()

**Comment by philippjfr** [comment]
With the small patch in #279 I get this:

![anim](https://user-images.githubusercontent.com/1550771/51148313-a7528280-1855-11e9-8867-16888233ca5b.gif)
