### ISSUE TITLE
Better versioning in documentation and examples

### ISSUE THREAD

**Issue by prusswan** [pyviz/geoviews#270]
First, thanks for providing a very useful project with many promising examples (I actually found holoviews first), but like others I have had problems setting them up. For example, on these pages http://geo.holoviews.org/Working_with_Bokeh.html and http://geo.holoviews.org/gallery/bokeh/tile_sources.html#bokeh-gallery-tile-sources I can see examples for using WMTS and tile sources. But it took me quite a while to realize that I needed to use `1.6.0` and I had `1.5.1` installed somehow in my Anaconda environment.

So, two things that will help:
1. Provide a changelog
2. Indicate version numbers in the documentation examples/gallery, so that users have some idea on what version of the package they will need. 

I understand there was some project restructuring that happened before, but better documentation will get this project out to more people...

**Comment by philippjfr** [comment]
Absolutely agree, versioning of docs is going to be a priority of mine and the changelog I've been overlooking due to time constraints. I'll be adding it in the new year and write a blog post to announce changes.

**Comment by philippjfr** [comment]
This discussion is captured by https://github.com/pyviz-dev/nbsite/issues/54 which applies to all our projects.
