### ISSUE TITLE
Reprojecting data to ccrs.Geostationary() leads to clipping and warped globe

### ISSUE THREAD

**Issue by kaedonkers** [pyviz/geoviews#306]
Hello,

I'm new to using `geoviews` and `bokeh` but have used `cartopy` and `matplotlib` a lot in the past.
I have loaded a `geoviews.Dataset` and am trying to reproject the data onto a `cartopy.crs.Geostationary()` view. However the data seems not to have reprojected and the whole globe projection is squashed.
Are these the expected default behaviours? How do I plot using `Geostationary` projection with `geoviews`? 

![poor_projection](https://user-images.githubusercontent.com/32906197/55149530-3d523580-5142-11e9-8974-44e45aa6c8b6.png)

**Comment by ahuang11** [comment]
Try setting central_longitude in the projection keyword.

```
import xarray as xr
import geoviews as gv
import holoviews as hv
import hvplot.xarray
import cartopy.crs as ccrs
hv.extension('bokeh')

ds = xr.tutorial.open_dataset('air_temperature').isel(time=0)

ds.hvplot('lon', 'lat', crs=ccrs.PlateCarree(),
          projection=ccrs.Geostationary(central_longitude=ds['lon'].mean().values)
          ) * gv.feature.coastline

ds.hvplot('lon', 'lat')
```

![image](https://user-images.githubusercontent.com/15331990/55603274-aaeffa00-571e-11e9-912c-5df077374ee6.png)

**Comment by kaedonkers** [comment]
Thanks @ahuang11. 

In the end this is the solution we came up with:
```python
import holoviews as hv
import geoviews as gv
import cartopy.crs as ccrs
from holoviews.operation.datashader import regrid
hv.extension('bokeh', logo=False)

cube = #load data using iris
dataset = gv.Dataset(cube, [coord.name() for coord in cube.dim_coords], label=cube.name())
image = regrid(dataset.to(gv.Image, kdims=['longitude', 'latitude'], dynamic=True))
image.opts(projection=ccrs.PlateCarree())
```
