### ISSUE TITLE
downloading features is crushing kernel in jupyter

### ISSUE THREAD

**Issue by DmitriyG228** [pyviz/geoviews#309]
Hi, downloading features is crushing kernel in jupyter on my computer.

the following code:
```
import geoviews.feature as gf
gf.borders
```

it is also printing the following output:

> Invalid argument (must be a Polygon)
> Geometry must be a Point or LineString

Thank you!

**Comment by philippjfr** [comment]
Could you provide versions of all relevant packages, i.e. geoviews, cartopy, fiona and shapely?

**Comment by philippjfr** [comment]
Closing as unreproducible.
