### ISSUE TITLE
Kernel Crash when global_extent=False

### ISSUE THREAD

**Issue by JeremyBYU** [pyviz/geoviews#313]
Following the example code here: http://geoviews.org/gallery/bokeh/world_population.html#bokeh-gallery-world-population

I modified for my data. It works fine if global_extent=True, but crashes the kernel when global_extent=False.
```
gps_gv = gv.Dataset(df_gps, kdims=['raw_theta'])
points_gps = gps_gv.to(gv.Points, ['raw_lon', 'raw_lat'], ['raw_theta'])

tiles = gv.tile_sources.Wikipedia

tiles * points_gps.opts(global_extent=False,width=600, height=600)
```
Python 3.6, Package versions:
```
geoviews                  1.6.2                      py_0    pyviz
holoviews                 1.12.1                     py_0    pyviz
```

**Comment by philippjfr** [comment]
Thanks for the issue, sorry I didn't reply earlier. This is likely related to the way you installed gdal, GEOS or one of the other C-dependencies. So without more detail on how you installed things we can't help.
