### ISSUE TITLE
Hover tooltips gv.RGB does not work, return ???

### ISSUE THREAD

**Issue by emryslda** [pyviz/geoviews#331]
Hy guys I am trying to plot an RGB image with geoviews using also the hover tooltips to display the Lat e Lon and RGB values.

1) 
```python
opt.default(opts.RGB( tools=['hover']))
rgb =gv.RGB((RGB['x'],RGB['y'],RGB.R,RGB.G, RGB.B),vdims=['R','G','B'], crs=crs)

```
where RGB is an xarray with R,G,B, Data Variables. Should I pass to gv.RGB another object? The plot is ok.

![2](https://user-images.githubusercontent.com/42739089/57970202-c5083380-797e-11e9-8713-16d23d8267b6.jpg)

2) for Lat e Lon coords I report another issue: 
if you use the following tooltips, you will get the right value but in meters. 
```python
tooltips=[
    ("lon", "$x"),
    ("lat", "$y")
   ]
```
if you use the CustomJSHover code, you will get the wrong projected value but in degrees and with a lot of digit after the comma that would be nice to cut. 
```python
lat_custom = CustomJSHover(code="""
    var projections = require("core/util/projections");
    var x = special_vars.x
    var y = special_vars.y
    var coords = projections.wgs84_mercator.inverse([x, y])
    return "" + coords[0]
""")

hover=HoverTool(
    tooltips=[( 'lat','@y{custom}' )],
    formatters=dict(y=lat_custom)
)

```
any idea?

**Comment by philippjfr** [comment]
Should have been fixed by:

https://github.com/pyviz/geoviews/issues/331

**Comment by philippjfr** [comment]
The second issue is already being discussed here: https://github.com/pyviz/geoviews/issues/251
