### ISSUE TITLE
Coloring polygons by categorical variable

### ISSUE THREAD

**Issue by hickman-santini** [pyviz/geoviews#337]
When using the `color_index` option on `Polygons`, how does geoviews decide how many discrete colors to use (how to group the indexes)?

Geoviews `Polygons` are terrific, I don't know what I'd do without them; however, I'm struggling to color my polygons by a categorical variable, or indeed a continuous, date-time variable. I can color by floats alright: ![(see)](https://user-images.githubusercontent.com/26146505/60837365-01455c80-a196-11e9-934a-a1dcdab930fd.png)
But when I try the following code, all the polygons are the same color, despite having different `filename`s:

```
    plot = tilesource.opts(width=TABLEWIDTH, height=int(TABLEWIDTH/2)) \
           * gv.Polygons(dataset, vdims=['filename', 'dttime']).opts(style=dict(alpha=0.4,line_color='red')).redim.range(Longitude=(-130, -70))
    plot.opts(
        opts.Polygons(color_index='filename', tools=['hover', 'pan', 'wheel_zoom'], show_legend=True)
    )  
```

![image](https://user-images.githubusercontent.com/26146505/60839028-2b008280-a19a-11e9-9f06-4e1e6031e19c.png)
If I replace `color_index`=`filename` (string) by `dttime` (datetime object), same problem, all purple.

I'm using:
```
>>> bokeh.__version__
'1.1.0'
>>> holoviews.__version__
'1.12.1'
>>> geoviews.__version__
'1.6.2.post8+g79a79fe'
```

**Comment by ahuang11** [comment]
I'm not too sure how to do it in plain Geoviews, but hvplot works nicely:
```
import geopandas
import hvplot.pandas

world = geopandas.read_file(geopandas.datasets.get_path('naturalearth_lowres'))
world.hvplot(color='continent')
```

![image](https://user-images.githubusercontent.com/15331990/60853274-2777f600-a1b0-11e9-8e20-a3c6878617e9.png)

**Comment by ahuang11** [comment]
Nevermind, you just have to change the colormap!
http://geoviews.org/user_guide/Geometries.html

```gv.Polygons(world, vdims=['continent']).opts(cmap='tab20')```

**Comment by hickman-santini** [comment]
@ahuang11 thank you, you're right! I had used `cmap` before. I'm not sure why I discounted it. With 'tab20', I get beautiful colors.
![image](https://user-images.githubusercontent.com/26146505/60915539-0ff54780-a25a-11e9-8e61-870cc6bb941a.png)

**Comment by hickman-santini** [comment]
@ahuang11 thank you, you're right! I had used cmap before. I'm not sure why I discounted it. With 'tab20', I get beautiful colors.
![image](https://user-images.githubusercontent.com/26146505/60915642-4f239880-a25a-11e9-978c-043eca58b676.png)

**Comment by jbednar** [comment]
Also note that colorcet offers 256-color categorical colormaps, if you have a lot of categories: http://colorcet.pyviz.org/user_guide/Categorical.html

**Comment by hickman-santini** [comment]
@jbednar that's terrific. I had never seen that before! For any noobs like me who may one day stumble on this, if you e.g. want to use the glasbey_hv colors, it's as easy as:
`from colorcet import glasbey_hv`
...`cmap='glasbey_hv'`...

**Comment by hickman-santini** [comment]
**Correction:** 'glasbey_hv' gets loaded without `colorcet`, idk, maybe through holoviews. Not sure how to get any other glasbey colors yet...

**Comment by jbednar** [comment]
Just importing colorcet should be sufficient to make the colormap available.  It's possible that holoviews is automatically importing colorcet if available, but if so that's unintentional, so always do `import colorcet` if you want to use a colorcet colormap.
