### ISSUE TITLE
Faulty grid lines handling

### ISSUE THREAD

**Issue by poplarShift** [pyviz/geoviews#343]
Before #308, the following failed:
```
import holoviews as hv
hv.extension('matplotlib')
import geoviews as gv # without this, works

(hv.Scatter([]) * hv.Scatter([])).opts(show_grid=True)
```
as was already noted in #307.
A similar issue is also at work in #332

However, the patch employed in #308, and my current draft of #332, (replacing cartopy's GeoAxes `gridlines` method with standard mpl `grid`) removes all the benefits of having cartopy handle the grid lines in the first place...

So what would be needed is some sort of logic that decides whether the elements in question are, in fact, GeoViews objects (or whether the Overlay is composed of actual geo objects), and hence if they are GeoAxes or just plain matplotlib ones; and THEN accordingly apply `gridlines` or `grid`.

**Comment by philippjfr** [comment]
Merged the
