### ISSUE TITLE
Incorrect values of lat/lon on hover using latest version

### ISSUE THREAD

**Issue by hdsingh** [pyviz/geoviews#347]
Correct hover values in `hv.__version__:  1.12.1`:
![Screenshot from 2019-08-09 12-03-24](https://user-images.githubusercontent.com/30382331/62759299-87f39f00-ba9e-11e9-94ac-d369f0165e87.png)

Incorrect hover values in `hv.__version__:  1.12.4`:
![Screenshot from 2019-08-09 12-03-41](https://user-images.githubusercontent.com/30382331/62759356-ac4f7b80-ba9e-11e9-896a-7c86e8c94063.png)

Reproducible example:
```python
import xarray as xr
import hvplot.xarray
import holoviews as hv
import cartopy.crs as ccrs
print("hv.__version__: ",hv.__version__)

url = 'http://opendap.co-ops.nos.noaa.gov/thredds/dodsC/NOAA/LOOFS/MODELS/201907/glofs.loofs.fields.forecast.20190720.t06z.nc'
data = xr.open_dataset(url)
data = data.set_coords(['lat','lon'])

mesh = data.air_u[-1:,:,:].hvplot.quadmesh(x='lon', y='lat', rasterize=True, crs=ccrs.PlateCarree())
mesh
```
Also correct behaviour is shown without using `crs`.

**Comment by fmaussion** [comment]
I've been hit by this as well. As a workaround I wanted to create a custom hover showing the z values only. 

I have a `vg.dataset` looking as following:

```python
dataset = gv.Dataset(ds, ['longitude', 'latitude'], 'trends', crs=crs.PlateCarree())
print(dataset)
:Dataset   [longitude,latitude]   (trends)
```

But when I create a custom hover, the values are not shown and I see a `???` instead:

```python
from bokeh.models import HoverTool
hover = HoverTool(
        tooltips=[
            ("Trend", "@trends"),
        ]
    )

image = dataset.to(gv.Image).redim.range(trends=(-1.5, 1.5))
plot = image.opts(cmap='RdBu_r', colorbar=True, width=1000, height=500, 
                  projection=crs.Mollweide(), tools=[hover], active_tools=['pan','wheel_zoom']) * gf.coastline
plot
```

![Selection_034](https://user-images.githubusercontent.com/10050469/63927292-4d4da880-ca45-11e9-84bc-466ef6af6ff3.png)

It's probably me doing something wrong here, but what?

**Comment by fmaussion** [comment]
Nevermind my question above, this seems to not yet be supported in Holoviews: https://github.com/pyviz/geoviews/issues/251

Using `@image` works (took me some time to find out)

**Comment by rsignell-usgs** [comment]
@jbednar , I'm hoping this is on the list of tasks to be done for Pangeo.   We would really like to stop pinning holoviews to 1.12.1.

**Comment by jsignell** [comment]
As a workaround, adding the `projection` arg seemed to fix this for me. The `projection` arg is meant to specify the target projection of the plot.

```python
import xarray as xr
import hvplot.xarray
import holoviews as hv
import cartopy.crs as ccrs
print("hv.__version__: ",hv.__version__)

url = 'http://opendap.co-ops.nos.noaa.gov/thredds/dodsC/NOAA/LOOFS/MODELS/201907/glofs.loofs.fields.forecast.20190720.t06z.nc'
data = xr.open_dataset(url)
data = data.set_coords(['lat','lon'])

mesh = data.air_u[-1:,:,:].hvplot.quadmesh(x='lon', y='lat', rasterize=True, 
                                           crs=ccrs.PlateCarree(), projection=ccrs.PlateCarree())
mesh
```
<img width="1002" alt="Screen Shot 2019-09-18 at 5 06 37 PM" src="https://user-images.githubusercontent.com/4806877/65186067-d3528300-da36-11e9-9c5a-20d435710de5.png">

**Comment by philippjfr** [comment]
So using latest holoviews and geoviews I actually can't reproduce this.

**Comment by philippjfr** [comment]
@jsignell Could you confirm?

**Comment by philippjfr** [comment]
Huh, very strange, suddenly I can reproduce it again.

**Comment by jsignell** [comment]
Maybe you left off `rasterize=True`?

**Comment by philippjfr** [comment]
So the very strange thing here is that it all seems to be set up correctly and it works when you do:

```python
pn.panel(hv.render(mesh))
```

But somehow when letting HoloViews render it, the `CustomJSHover` does not get called.

**Comment by tom-andersson** [comment]
I'm getting the same hover issue (lat/lon show up as projected coords, not in degrees) with `hvplot=0.7.2`, `geoviews=1.9.1`, `bokeh=2.3.0`. I see from digging through issues like this that the bug was meant to be fixed a couple years ago. Any advice?
