### ISSUE TITLE
Error message from numpy when using gv.Image

### ISSUE THREAD

**Issue by khider** [pyviz/geoviews#348]
I've been trying to use the gv.Image function to view netcdf files. It works well on the example but when using another netcdf file, I run into the following error:
 ---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/anaconda3/lib/python3.6/site-packages/IPython/core/formatters.py in __call__(self, obj, include, exclude)
    968 
    969             if method is not None:
--> 970                 return method(include=include, exclude=exclude)
    971             return None
    972         else:

/anaconda3/lib/python3.6/site-packages/holoviews/core/dimension.py in _repr_mimebundle_(self, include, exclude)
   1438         combined and returned.
   1439         """
-> 1440         return Store.render(self)
   1441 
   1442 

/anaconda3/lib/python3.6/site-packages/holoviews/core/options.py in render(cls, obj)
   1514         data, metadata = {}, {}
   1515         for hook in hooks:
-> 1516             ret = hook(obj)
   1517             if ret is None:
   1518                 continue

/anaconda3/lib/python3.6/site-packages/holoviews/ipython/display_hooks.py in pprint_display(obj)
    275     if not ip.display_formatter.formatters['text/plain'].pprint:
    276         return None
--> 277     return display(obj, raw_output=True)
    278 
    279 

/anaconda3/lib/python3.6/site-packages/holoviews/ipython/display_hooks.py in display(obj, raw_output, **kwargs)
    251     elif isinstance(obj, (HoloMap, DynamicMap)):
    252         with option_state(obj):
--> 253             output = map_display(obj)
    254     elif isinstance(obj, Plot):
    255         output = render(obj)

/anaconda3/lib/python3.6/site-packages/holoviews/ipython/display_hooks.py in wrapped(element)
    140         try:
    141             max_frames = OutputSettings.options['max_frames']
--> 142             mimebundle = fn(element, max_frames=max_frames)
    143             if mimebundle is None:
    144                 return {}, {}

/anaconda3/lib/python3.6/site-packages/holoviews/ipython/display_hooks.py in map_display(vmap, max_frames)
    200         return None
    201 
--> 202     return render(vmap)
    203 
    204 

/anaconda3/lib/python3.6/site-packages/holoviews/ipython/display_hooks.py in render(obj, **kwargs)
     63         renderer = renderer.instance(fig='png')
     64 
---> 65     return renderer.components(obj, **kwargs)
     66 
     67 

/anaconda3/lib/python3.6/site-packages/holoviews/plotting/bokeh/renderer.py in components(self, obj, fmt, comm, **kwargs)
    247         # Bokeh has to handle comms directly in <0.12.15
    248         comm = False if bokeh_version < '0.12.15' else comm
--> 249         return super(BokehRenderer, self).components(obj,fmt, comm, **kwargs)
    250 
    251 

/anaconda3/lib/python3.6/site-packages/holoviews/plotting/renderer.py in components(self, obj, fmt, comm, **kwargs)
    324         data, metadata = {}, {}
    325         if isinstance(plot, NdWidget):
--> 326             js, html = plot(as_script=True)
    327             plot_id = plot.plot_id
    328             widget_id = plot.id

/anaconda3/lib/python3.6/site-packages/holoviews/plotting/widgets/__init__.py in __call__(self, as_script)
    172 
    173     def __call__(self, as_script=False):
--> 174         data = self._get_data()
    175         html = self.render_html(data)
    176         js = self.render_js(data)

/anaconda3/lib/python3.6/site-packages/holoviews/plotting/bokeh/widgets.py in _get_data(self)
    316     def _get_data(self):
    317         if not self.plot.dynamic:
--> 318             widgets, _, _ = self.get_widgets()
    319             key = tuple(w['value'] for w in widgets)
    320             self.plot.update(key)

/anaconda3/lib/python3.6/site-packages/holoviews/plotting/widgets/__init__.py in get_widgets(self)
    333             else:
    334                 widget_data = self._get_static_widget(idx, dim, self.mock_obj, hierarchy,
--> 335                                                       init_dim_vals)
    336             init_dim_vals.append(widget_data['init_val'])
    337             visibility = '' if widget_data.get('visible', True) else 'display: none'

/anaconda3/lib/python3.6/site-packages/holoviews/plotting/widgets/__init__.py in _get_static_widget(cls, idx, dim, mock_obj, hierarchy, init_dim_vals)
    371         elif isnumeric(values[0]):
    372             values = sorted(values)
--> 373             dim_vals = [round(v, 10) for v in values]
    374             if next_vals:
    375                 next_vals = {round(k, 10): [round(v, 10) if isnumeric(v) else v

/anaconda3/lib/python3.6/site-packages/holoviews/plotting/widgets/__init__.py in <listcomp>(.0)
    371         elif isnumeric(values[0]):
    372             values = sorted(values)
--> 373             dim_vals = [round(v, 10) for v in values]
    374             if next_vals:
    375                 next_vals = {round(k, 10): [round(v, 10) if isnumeric(v) else v

TypeError: ufunc 'rint' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

Any suggestions?

**Comment by jbednar** [comment]
Do you have a shareable file that would cause the error? If everything is being used correctly then it sounds like one of the dimensions has an unusual type that we haven't previously encountered, but beyond that it's hard to tell from the error message alone.

**Comment by khider** [comment]
Yes, sorry the notification got buried in my junk folder. 

See here: https://github.com/mintproject/Topoflow_Viz/blob/master/June_20_67_2D-Q_5.nc

**Comment by jbednar** [comment]
Great, thanks!  A snippet of code that reproduces the error given that file would be very helpful as well.

**Comment by philippjfr** [comment]
The issue still lacks a reproducible example, that said starting in holoviews 1.13.0 which has better support for timedeltas this will work just fine:

```
da = xr.open_dataset('/Users/philippjfr/Downloads/June_20_67_2D-Q_5.nc')
da  = da.assign_coords({'nx': np.arange(29), 'ny': np.arange(44)})
da.hvplot.image('nx', 'ny')
```

The data is also not geographic (or the geographic coordinates are missing), so I'll close it here.
