### ISSUE TITLE
mpl grid labels for platecarree/mercator

### ISSUE THREAD

**Issue by ahuang11** [pyviz/geoviews#350]
```
import hvplot.xarray
import xarray as xr

ds = xr.tutorial.open_dataset('air_temperature').isel(time=0)
ds.hvplot.image('lon', 'lat', geo=True, xaxis='bottom')
```

I think just need to do if platecarree/mercator
`ax.gridlines(draw_labels=True)`
else
`ax.gridlines()`

https://github.com/pyviz/geoviews/blob/79a79fe8cff8f18126097487e2b4440da4e7678c/geoviews/plotting/mpl/__init__.py#L111

**Comment by philippjfr** [comment]
+1, would readily merge a PR like this.
