### ISSUE TITLE
FilledContours is inconsistent with hv.operations.contours() and missing levels as keyword arg

### ISSUE THREAD

**Issue by ahuang11** [pyviz/geoviews#353]
I expected the geoviews equivalent of `hv.operations.contours(levels=levels)` or `ds.hvplot.contourf(levels=levels)` would be `gv.FilledContours(levels=levels)` but levels is not a keyword;

but I guess it's callable through `gv.FilledContours().opts(levels=levels)`

**Comment by philippjfr** [comment]
levels is a plotting level concept, so it wouldn't make sense to declare as part of the element itself.
