### ISSUE TITLE
python2.7 import error through fiona

### ISSUE THREAD

**Issue by aschueth** [pyviz/geoviews#361]
I am trying to get geoviews to work in a fresh python2.7 environment on MacOS High Sierra. If I install fiona alone and try to import it, it works no problem. But when I install geoviews, it uses fiona-1.8.4. When I try to import fiona (or geoviews) I get the following error.

In [1]: import fiona
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-4c762272c079> in <module>()
----> 1 import fiona

/Users/alexschueth/miniconda3/envs/radarproc3/lib/python2.7/site-packages/fiona/__init__.py in <module>()
     81     os.environ["PATH"] = os.environ["PATH"] + ";" + libdir
     82
---> 83 from fiona.collection import BytesCollection, Collection
     84 from fiona.drvsupport import supported_drivers
     85 from fiona.env import ensure_env_with_credentials, Env

/Users/alexschueth/miniconda3/envs/radarproc3/lib/python2.7/site-packages/fiona/collection.py in <module>()
      7
      8 from fiona import compat, vfs
----> 9 from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
     10 from fiona.ogrext import Session, WritingSession
     11 from fiona.ogrext import buffer_to_virtual_file, remove_virtual_file, GEOMETRY_TYPES

ImportError: dlopen(/Users/alexschueth/miniconda3/envs/radarproc3/lib/python2.7/site-packages/fiona/ogrext.so, 2): Library not loaded: @rpath/libpoppler.76.dylib
  Referenced from: /Users/alexschueth/miniconda3/envs/radarproc3/lib/libgdal.20.dylib
  Reason: image not found

**Comment by aschueth** [comment]
This is not a python2.7 problem, rather when installing from conda-forge it pulls the wrong (old) version of fiona. This can be fixed by forcing fiona=1.8.6

**Comment by jsignell** [comment]
I can't see any fiona pinning in the [geoviews dependency list](https://github.com/regro-cf-autotick-bot/geoviews-feedstock/blob/961577af6bce4a4a910169ef800694f43a347b71/recipe/meta.yaml), possibly one of the other dependencies are pinning it? If so the issue should be raised with them.
