### ISSUE TITLE
change detection - dynamic choropleth using slider

### ISSUE THREAD

**Issue by eotp** [pyviz/geoviews#71]
I am struggling to construct dynamic choropleth maps, that correspond to different time stamps, and which are controllable by a slider.  An example could be to visualize the change within a particular region from one poll to another using the slider.

I am thankful for any advise, especially with respect to an implementation using the Bokeh backend.

**Comment by philippjfr** [comment]
Sorry we never got to this. The best approach here would be to use geopandas and update the column containing the values.
