### ISSUE TITLE
Export Geoviews (Bokeh Backend) to standalone HTML

### ISSUE THREAD

**Issue by abanduch** [pyviz/geoviews#74]
I am struggling to find the documentation or examples (if this is even possible) of exporting a Geoviews map/chart along with its Bokeh features to a standalone HTML document.  Mainly, I am looking for a way to share the charts I make with people who don't necessarily need or know the code.

**Comment by bentice** [comment]
http://holoviews.org/user_guide/Deploying_Bokeh_Apps.html

**Comment by philippjfr** [comment]
In the next release you will also be able to use ``hv.save``.
